# Library: Numpy

In [1]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
print(a[0])

[1 2 3]


In [23]:
new = np.append(a, [13, 14, 15])
new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
# menghapus indeks ke2 dan 4
np.delete(a, [2, 4])

array([ 1,  2,  4,  6,  7,  8,  9, 10, 11, 12])

In [39]:
# menghitung dimensi arraya.ndim
a.ndim

2

In [35]:
# menghitung ukuran array, yaitu 4x3
a.shape

(4, 3)

In [34]:
# menghitung berapa banyak item dalam array
a.size

12

In [45]:
# ubah bentuk array
a.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [47]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
arr.reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [50]:
# fungsi newaxis sama dengan reshape
arr[np.newaxis].shape

(1, 2, 4)

In [ ]:
# array untuk prime number
lower = 0
upper = 0
while(i >1):
    for i in range()

In [7]:
b = np.array([[0., 0., 0.], [1., 1., 1.]])
b

array([[0., 0., 0.],
       [1., 1., 1.]])

In [29]:
c = np.array([3, 1, 2, 0])
np.sort(c)

array([0, 1, 2, 3])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [15]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexing dan Slicing

In [52]:
mylist = [5, 7, 9, 1, 3, 2]
mylist
# np.sort(mylist)

[5, 7, 9, 1, 3, 2]

In [58]:
newlist = np.sort(mylist)
newlist

array([1, 2, 3, 5, 7, 9])

In [63]:
newlist[1: -1]

array([2, 3, 5, 7])

In [83]:
newlist[:6]

array([1, 2, 3, 5, 7, 9])

In [77]:
new = np.append(newlist, 10)
new

array([ 1,  2,  3,  5,  7,  9, 10])

In [78]:
new[(new > 3) & (new % 2 ==0) ]

array([10])

In [86]:
baru = [4, 5, 6, 7, 8, 9]
baru

[4, 5, 6, 7, 8, 9]

In [88]:
x = np.vstack((newlist, baru))
x

array([[1, 2, 3, 5, 7, 9],
       [4, 5, 6, 7, 8, 9]])

In [95]:
x.reshape(2, 2, 3)

array([[[1, 2, 3],
        [5, 7, 9]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [129]:
x1 = np.array([1, 2, 3, 4, 5, 6])
x1.reshape(2, 1, 3)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [93]:
np.hstack((newlist, baru))

array([1, 2, 3, 5, 7, 9, 4, 5, 6, 7, 8, 9])

In [94]:
np.hsplit(newlist, 3)

[array([1, 2]), array([3, 5]), array([7, 9])]

In [97]:
# bikin salinan/copy 
baru = np.hsplit(newlist, 3).copy()
baru

[array([1, 2]), array([3, 5]), array([7, 9])]

In [98]:
# bikin view
baru_lagi = a.view()
baru_lagi

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Basic Operations

In [121]:
m1 = np.array([[1, 2, 3], [7, 8, 9]])
m2 = np.array([4, 5, 6])

In [108]:
m1+m2

array([5, 7, 9])

In [111]:
m2-m1

array([3, 3, 3])

In [112]:
m1 * m2

array([ 4, 10, 18])

In [113]:
m2/m1

array([4. , 2.5, 2. ])

In [116]:
m1.sum()

6

In [117]:
m2.sum()

15

In [122]:
m1.sum(axis=1)

array([ 6, 24])

In [124]:
np.random.random((3, 3))

array([[0.08528794, 0.80042852, 0.28825985],
       [0.84644606, 0.96068313, 0.3152726 ],
       [0.79948852, 0.52911428, 0.0856206 ]])

In [131]:
# transpose
m1.T

array([[1, 7],
       [2, 8],
       [3, 9]])